kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: "*.systemtracker.no-ip.org"
    - op: add
      path: /apiServer/certSANs/-
      value: "192.168.0.5"
    - op: add
      path: /apiServer/certSANs/-
      value: "84.214.176.152"
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  ipFamily: ipv4
  apiServerAddress: "192.168.0.5"
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP    
  - containerPort: 15012
    hostPort: 15012
    listenAddress: "0.0.0.0"
    protocol: TCP      
  - containerPort: 15021
    hostPort: 15021
    listenAddress: "0.0.0.0"
    protocol: TCP   
  - containerPort: 15443
    hostPort: 15443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP   
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "0.0.0.0"
    protocol: TCP     
  - containerPort: 30021
    hostPort: 30021
    listenAddress: "0.0.0.0"
    protocol: TCP                 
  - containerPort: 31624
    hostPort: 31624
    listenAddress: "0.0.0.0"
    protocol: TCP     
  - containerPort: 31027
    hostPort: 31027
    listenAddress: "0.0.0.0"
    protocol: TCP                     
- role: worker
- role: worker
- role: worker
